version: "3"

services:
  react_app:
    container_name: react_app
    image: amtoft/devops_react_app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    restart: always
