version: "3"

services:
  react_app:
    container_name: react_app
    image: devops_react_app:latest
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:3000"
    restart: always